### ISSUE TITLE
[Help wanted] buffer names always defaults to "No Name"

### ISSUE THREAD

**Issue by UpsideDownFoxxo** [nanozuki/tabby.nvim#160] opened 2024-11-13 01:09 UTC
I wanted to finally make my own configuration for Tabby after my old one broke when updating.
I grabbed the [example config](https://github.com/nanozuki/tabby.nvim?tab=readme-ov-file#setup-tabbynvim) as a base, but all the window titles default to "No Name" in it. Is there additional config that is needed for buffer names to work, or is this a bug?

I'm using Lazyvim 13 and the `e02a28d` Tabby commit.

**Comment by nanozuki** [comment] 2024-11-13 01:24
I reproduce this issue. It may be a bug or I need to update my example config. I will handle it.

**Comment by nanozuki** [comment] 2024-11-13 02:12
Fixed in latest commit t0d5af

**Comment by nanozuki** [comment] 2024-11-19 08:18
@mikaraunio I cannot reproduce. Can you introduce me to the config and reproduce the steps?

Sometimes the luac cache may cause problems; you can also try to remove it. The Default path of cache (if you use XDG directories) is `~/.cache/nvim/luac/`

**Comment by mikaraunio** [comment] 2024-11-27 06:31
It is probably because I have a very old config (simplified version below). It seems I was using `require('tabby.feature.buf_name').get()` with the current _window_ id, which apparently used to work, but does not anymore.

Replacing `cur_win` with `vim.fn.winbufnr(cur_win)` does give me the correct filename, but strangely, it gives the current path for unnamed buffers instead of `[No Name]`.

```lua
local function name_fallback(tabid)
  local cur_win = require('tabby.module.api').get_tab_current_win(tabid)
  if require('tabby.module.api').is_float_win(cur_win) then
    return '[Floating]'
  else
    return require('tabby.feature.buf_name').get(cur_win)
  end
end

require('tabby.tabline').set(
  function(line)
    ...
  end,
  {
    tab_name = {
      name_fallback = name_fallback
    },
  }
)
```

**Comment by nanozuki** [comment] 2024-12-01 13:20
I think I removed some duplicated events. Now, it proves I was wrong. Thanks everyone.

**Closed** 2024-12-01 13:22 UTC
Labels: bug
