### ISSUE TITLE
Session not saving tabs

### ISSUE THREAD

**Issue by augustocdias** [nanozuki/tabby.nvim#149] opened 2024-07-31 20:30 UTC
I use `auto-session` for storing and restoring sessions and my `sessionoptions` is like this:

```lua
        vim.o.sessionoptions = 'buffers,curdir,folds,help,tabpages,winsize,resize,winpos,terminal,globals'
```

When I restore the session no tab is restored to the state I saved. If I create a new tab it will preserve the names I created previously, so that part at least is working as intended.  I was expecting the tabs would be restored with their windows layouts as I saved them...

**Comment by nanozuki** [comment] 2024-07-31 22:33
What's your config and version for tabby? I can not reproduce this bug.

**Comment by augustocdias** [comment] 2024-08-01 05:50
it happened pretty consistently with this config

```lua
vim.env.LAZY_STDPATH = '.tabby'
load(vim.fn.system('curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua'))()
vim.o.sessionoptions = 'buffers,curdir,folds,help,tabpages,winsize,resize,winpos,terminal,globals'

require('lazy.minit').repro({
    spec = {
        {
            'nanozuki/tabby.nvim',
            config = function()
                require('tabby.tabline').use_preset('tab_only', {
                    nerdfont = true, -- whether use nerdfont
                })
            end,
        },
        {
            'rmagatti/auto-session',
            opts = {
                auto_session_enabled = true, -- enables auto save and auto restore
                auto_restore_enabled = true, -- enables auto restore if session for cwd exists
                auto_session_create_enabled = false, -- disables auto session creation
                cwd_change_handling = {
                    restore_upcoming_session = true,
                    pre_cwd_changed_hook = function()
                        require('sidebar'):close()
                    end,
                    post_cwd_changed_hook = function()
                        require('lualine').refresh()
                    end,
                },
                session_lens = {
                    theme_conf = { border = false },
                    previewer = true,
                },
            },
        },
    },
})
```

**Comment by nanozuki** [comment] 2024-08-01 06:30
It seems that buffers of some types are wiped in the session file, such as "terminal", "netrw".. If all windows are "file window", there is no problem. I think this maybe caused by  `auto-sessioon` or neovim. I will check further...

**Comment by augustocdias** [comment] 2024-08-01 06:32
When I tried I had 2 buffers of 2 different files. One opened in each tab

**Comment by nanozuki** [comment] 2024-08-01 06:44
Oh, you should set `auto_session_create_enabled` to `true,` or you can call the command `SessionSave` to create one manually; otherwise, `auto-session` wouldn't create a new session for you.

But terminal buffers gone is a big problem.

Btw, what's your neovim version (`nvim -v`)? Mine is:

```shell
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713773202
```

**Comment by augustocdias** [comment] 2024-08-01 06:48
> Oh, you should set `auto_session_create_enabled` to `true,` or you can call the command `SessionSave` to create one manually; otherwise, `auto-session` wouldn't create a new session for you.

I know. I did that.

here's the contents of the session:

```vim
let SessionLoad = 1
let s:so_save = &g:so | let s:siso_save = &g:siso | setg so=0 siso=0 | setl so=-1 siso=-1
let v:this_session=expand("<sfile>:p")
let TabbyTabNames = "{\"1\":\"tab1\",\"2\":\"tab2\"}"
silent only
silent tabonly
cd ~/nvim-tests
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
let s:shortmess_save = &shortmess
if &shortmess =~ 'A'
  set shortmess=aoOA
else
  set shortmess=aoO
endif
badd +1 minimal.lua
badd +1 minimal.lualine.lua
argglobal
%argdel
set lines=66 columns=365
edit minimal.lua
argglobal
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
silent! normal! zE
let &fdl = &fdl
let s:l = 4 - ((3 * winheight(0) + 32) / 64)
if s:l < 1 | let s:l = 1 | endif
keepjumps exe s:l
normal! zt
keepjumps 4
normal! 0
tabnext 1
if exists('s:wipebuf') && len(win_findbuf(s:wipebuf)) == 0 && getbufvar(s:wipebuf, '&buftype') isnot# 'terminal'
  silent exe 'bwipe ' . s:wipebuf
endif
unlet! s:wipebuf
set winheight=1 winwidth=20
let &shortmess = s:shortmess_save
let s:sx = expand("<sfile>:p:r")."x.vim"
if filereadable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &g:so = s:so_save | let &g:siso = s:siso_save
set hlsearch
doautoall SessionLoadPost
unlet SessionLoad
" vim: set ft=vim :
```

nvim version:

```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

**Comment by augustocdias** [comment] 2024-08-01 07:17
On nvim nightly it seems to work.

**Comment by nanozuki** [comment] 2024-08-01 07:56
Seems that this is a bug of neovim. In fact, `tabby. nvm` only affect one global variable for persistent tab names. Just one line in the session file:

```vim
let TabbyTabNames = "{\"1\":\"tab1\",\"2\":\"tab2\"}"
```

I keep this issue open to clear exactly what happens.

**Comment by nanozuki** [comment] 2024-08-05 23:34
I reported the issue of the terminal window closing in auto-session. Anyone who has problem with this can check in: https://github.com/rmagatti/auto-session/issues/342

**Closed by nanozuki** 2024-08-05 23:34 UTC
Labels: upstream
